name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ 3.9 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: quenelles-dev
        environment-file: dev-environment.yml
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge

    - name: Install quenelles
      run: |
        pip install -e .
        pip install https://github.com/davidbrochart/kernel_driver/archive/main.zip --ignore-installed 

    - name: Check style
      run: |
        black --check quenelles
        flake8 --max-line-length 100 quenelles

    - name: Run tests
      run: |
        quenelles --help
        quenelles install python
        test -f ${CONDA_PREFIX}/share/jupyter/kernels/quenelles/kernel.json
        py.test quenelles/tests
